### ISSUE TITLE
尝试转换zrender的js为CommonJS时，部分文件报错

### ISSUE THREAD

**Issue by airyland** [army8735/ranma#4]
https://github.com/ecomfe/zrender/blob/master/src/dep/excanvas.js

``` shell
    if(ast.first() && ast.first().name() == Es6Node.MODULEBODY) {
           ^
TypeError: Object #<Object> has no method 'first'
    at Object.exports.analyse (e:\code\zrender\node_modules\ranma\type.js:94:12)
    at Object.exports.isCommonJS (e:\code\zrender\node_modules\ranma\type.js:119:11)
    at modify.fileModifier (e:\code\zrender\gulpfile.js:10:29)
    at DestroyableTransform._transform (e:\code\zrender\node_modules\gulp-modify\index.js:18:21)
    at DestroyableTransform.Transform._read (e:\code\zrender\node_modules\through2\node_modules\readable-stream\lib\_st
eam_transform.js:184:10)
    at DestroyableTransform.Transform._write (e:\code\zrender\node_modules\through2\node_modules\readable-stream\lib\_s
ream_transform.js:172:12)
    at doWrite (e:\code\zrender\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at writeOrBuffer (e:\code\zrender\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (e:\code\zrender\node_modules\through2\node_modules\readable-stream\lib\_str
am_writable.js:194:11)
    at write (e:\code\zrender\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    at flow (e:\code\zrender\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (e:\code\zrender\node_modules\through2\node_modules\readable-stream\lib\_str
am_readable.js:664:5)
```

**Comment by army8735** [comment]
好的我看看
